# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Sat, 22 Mar 2014 21:47:30 +0000
*               @ALL          1
*               @user         8
