<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: joebordes
 * Date: Wed, 30 Sep 2015 19:12:47 +0200
 */

$conf['title'] = 'coreBOS';
$conf['template'] = 'codowik-master';
$conf['license'] = 'cc-by-sa';
$conf['useheading'] = '1';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register,profile_delete';
$conf['remote'] = 1;
$conf['remoteuser'] = 'coreboshelp';
$conf['subscribers'] = 1;
$conf['mailfrom'] = 'corebos@tsolucio.com';
$conf['sitemap'] = 5;
$conf['plugin']['mantis']['mantis_server'] = 'http://corebos.org/development/api/soap/mantisconnect.php?wsdl';
$conf['plugin']['mantis']['mantis_user'] = 'xxx';
$conf['plugin']['mantis']['mantis_password'] = 'xxx';
$conf['plugin']['translation']['translations'] = 'en es';
$conf['plugin']['translation']['display'] = 'langcode';
$conf['plugin']['translation']['translateui'] = 1;
$conf['plugin']['translation']['redirectstart'] = 1;
$conf['plugin']['facebooklike']['layout'] = 'button_count';

// end auto-generated content
