<?php

//This file is autogenerated. You can change configuration from admin menu.
//For more information about possible options, please consult website.

$conf['ndqerr'] = 'warning';
$conf['regerr'] = 'error';
$conf['option'] = 'nodisp';
$conf['badopt'] = 'nowarn';
$conf['ignopt'] = 'warning';
$conf['dispheadl'] = 'nodisp';


?>